[package]
name = "ingameime-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# JNI - use 0.22.4 for stable API
jni = "0.22.4"
jni-sys = "0.4"

# windows
[target.'cfg(windows)'.dependencies]
windows-core = "0.62.2"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_UI_Input_Ime",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_UI_TextServices",
    "Win32_Globalization",
    "Win32_System_LibraryLoader",
    "Win32_System_Variant"
] }